export default [
    {
        location: "Cyprus",
        title: "Larnaca",
        startDate: 2015,
        endDate: 2015,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1602521163379-79fba9eac5e6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=686&q=80",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non rhoncus urna. Duis lobortis nunc at risus lacinia pellentesque. Duis auctor imperdiet porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum dapibus tempor massa, vitae aliquet libero porttitor quis.",
    },
    {
        id: 2,
        location: "Italy",
        title: "Rome",
        startDate: 2016,
        endDate: 2016,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1581274050302-581149d3b4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
        description: "Vestibulum id sollicitudin dui, eget elementum enim. Duis at metus augue. Donec quis tincidunt metus. Cras in condimentum tellus, eu viverra turpis. Cras condimentum, orci ut scelerisque tincidunt, turpis sem molestie neque, id consequat ante leo eu justo. Phasellus sed lorem ac turpis mollis dictum et id magna. Praesent dictum tellus id justo eleifend, non tempor erat pellentesque",
    },
    {
        id: 3,
        location: "Greece",
        title: "Athens",
        startDate: 2017,
        endDate: 2017,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1605153322277-dd0d7f608b4d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80",
        description: "Maecenas et tellus turpis. Suspendisse pharetra purus vitae pretium convallis. Etiam quis elit urna. Vestibulum tempus euismod neque vel molestie. Aliquam sit amet erat id arcu pharetra placerat. Integer commodo consequat tincidunt. Vivamus at eros sem. Phasellus sed ultrices ligula. Nam in neque sit amet ligula luctus ullamcorper id id est.",
    },
    {
        id: 4,
        location: "Czechia",
        title: "Prague",
        startDate: 2018,
        endDate: 2018,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1580852710598-96912fc48065?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80",
        description: "Phasellus mollis purus ac sapien bibendum, eget ultrices purus fringilla. Fusce efficitur non dui id mattis. Proin quis lacinia lacus. Aliquam tristique bibendum quam, quis sagittis urna. Quisque facilisis porttitor augue. Vivamus pellentesque nunc sed hendrerit feugiat.",
    },
    {
        id: 5,
        location: "Italy",
        title: "Milan",
        startDate: 2019,
        endDate: 2019,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1606299966686-33b993c30bd0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80",
        description: "Donec malesuada augue ac nisl commodo mattis. Duis sagittis neque vitae ante malesuada suscipit. Aenean ornare consequat congue. Morbi nec venenatis ante, et molestie orci.",
    },
    {
        id: 6,
        location: "Austria",
        title: "Vienna",
        startDate: 2020,
        endDate: 2020,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1573167443185-6755c7b21ca1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dolor mi, sodales ac lectus in, rhoncus tincidunt ligula. In iaculis ut massa ac finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer id malesuada dolor.",
    },
    {
        id: 7,
        location: "Malta",
        title: "Valletta",
        startDate: 2021,
        endDate: 2021,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1513543806865-85e29a7c0352?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        description: "Pellentesque placerat magna eget tristique tincidunt. Nullam dignissim, tellus vitae pharetra imperdiet, nunc justo tristique quam, sollicitudin egestas mi est at sem. Proin ac feugiat velit. Donec nec dapibus turpis.",
    },
    {
        id: 8,
        location: "Montenegro",
        title: "Kotor",
        startDate: 2022,
        endDate: 2022,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1558971067-6edfd413e506?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80",
        description: "Proin faucibus nec dui ut vulputate. Integer sit amet sollicitudin nisi, id vulputate sem. Nulla a ultrices mi. Vestibulum volutpat condimentum lectus a ornare.",
    },
    {
        id: 9,
        location: "Hungary",
        title: "Budapest",
        startDate: 2022,
        endDate: 2022,
        googleMapsLink: "https://googlemaps.com",
        imageUrl: "https://images.unsplash.com/photo-1541343672885-9be56236302a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        description: "Maecenas nec justo eleifend, bibendum dolor auctor, finibus lacus. Donec hendrerit, diam a posuere bibendum, ex velit ullamcorper nisl, quis faucibus purus leo quis dui. Integer sed rutrum sapien.",
    }
]
